CREATE TABLE EMPLOYER (
	ID INTEGER NOT NULL,
	EMPL_NAME VARCHAR(100) NOT NULL,
	CONSTRAINT EMPLOYER_PK PRIMARY KEY (ID)
);

INSERT INTO EMPLOYER (ID,EMPL_NAME) VALUES (1,'Рязанов Валентин Сергеевич');
INSERT INTO EMPLOYER (ID,EMPL_NAME) VALUES (2,'Морозков Андрей');
INSERT INTO EMPLOYER (ID,EMPL_NAME) VALUES (3,'Егоров Павел Валентинович');
INSERT INTO EMPLOYER (ID,EMPL_NAME) VALUES (4,'Цветков Евгений');

CREATE TABLE POST (
	ID INTEGER NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CONSTRAINT POST_PK PRIMARY KEY (ID)
);

INSERT INTO POST (ID,TITLE) VALUES (1,'начальник отдела');
INSERT INTO POST (ID,TITLE) VALUES (2,'зам. начальника отдела');
INSERT INTO POST (ID,TITLE) VALUES (3,'инженер-программист');

CREATE TABLE POST_OF_EMPLOYERS (
	ID_EMPLOYER INTEGER NOT NULL,
	ID_POST INTEGER NOT NULL,
	CONSTRAINT POST_OF_EMPLOYERS_FK FOREIGN KEY (ID_EMPLOYER) REFERENCES EMPLOYER(ID),
	CONSTRAINT POST_OF_EMPLOYERS_FK_1 FOREIGN KEY (ID_POST) REFERENCES POST(ID)
);

INSERT INTO POST_OF_EMPLOYERS (ID_EMPLOYER,ID_POST) VALUES (1,1);
INSERT INTO POST_OF_EMPLOYERS (ID_EMPLOYER,ID_POST) VALUES (2,2);
INSERT INTO POST_OF_EMPLOYERS (ID_EMPLOYER,ID_POST) VALUES (3,3);
INSERT INTO POST_OF_EMPLOYERS (ID_EMPLOYER,ID_POST) VALUES (4,3);

